[tox]
envlist=
    py27-django{17,18,19,110,111},
    py34-django{17,18,19,110,111},
    py35-django{18,19,110,111},
    py36-django{18,19,110,111},
    flake8

[testenv]
changedir=
    oidc_provider
deps =
    mock
    psycopg2
    pytest
    pytest-django
    pytest-flake8
    pytest-cov
    django17: django>=1.7,<1.8
    django18: django>=1.8,<1.9
    django19: django>=1.9,<1.10
    django110: django>=1.10,<1.11
    django111: django>=1.11,<1.12
    django20: django>=2.0,<2.1
commands =
    coverage run setup.py test

[testenv:clean]

commands=
    coverage erase

[testenv:stats]

commands=
    coverage report -m

[testenv:flake8]
basepython=python
deps=flake8
commands =
    flake8 --max-line-length=120
